### ISSUE TITLE
camera.yaml

### ISSUE THREAD

**Issue by Jai-GAY** [slowrunner/GoPi5Go#1]
Where can I reference the camera-calibrated data?
[params_file:=/home/pi/GoPi5Go/ros2ws/params/camera.yaml](https://github.com/slowrunner/GoPi5Go/tree/main/systests/aruco#ros2-aruco-markers)

Can I reference [it from here](https://github.com/slowrunner/HumbleDave2/blob/main/ros2ws/params/camera.yaml)?

**Comment by slowrunner** [comment]
I do not understand the question.

The Luxonis depthai_ros_driver package has default calibrations for  the Luxonis Oak-D-lite and Oak-D-W97 cameras which are used if not specified in the launch.  The launch I use is:

https://github.com/slowrunner/GoPi5Go/blob/e8a7ece4a56c2ad6b6283edc4332515e77a095c0/ros2ws/cmds/launch_camera.sh
```
ubuntu@HumbleD:~/HumbleDave2/ros2ws$ more cmds/launch_camera.sh 
#!/bin/bash


# ros2 topic echo --once --flow-style /color/mobilenet_detections 

# 0            "background",
# 1           "aeroplane",
# 2           "bicycle",
# 3           "bird",
# 4           "boat",
# 5           "bottle",
# 6           "bus",
# 7           "car",
# 8           "cat",
# 9           "chair",
# 10           "cow",
# 11           "diningtable",
# 12           "dog",
# 13           "horse",
# 14           "motorbike",
# 15           "person",
# 16           "pottedplant",
# 17           "sheep",
# 18           "sofa",
# 19           "train",
# 20          "tvmonitor"


dt=`(uptime)`
echo -e "\n ${dt}"
echo -e "LAUNCHING OAK-D-W97 camera.launch.py WITH params/camera.yaml (mobilenet + RGBD)"
echo -e "ros2 launch depthai_ros_driver camera.launch.py camera_model:=OAK-D-W params_file:=/home/pi/GoPi5Go/ros2ws/params/camera.yaml\n"
ros2 launch depthai_ros_driver camera.launch.py camera_model:=OAK-D-W params_file:=/home/pi/GoPi5Go/ros2ws/params/camera.yaml


dt=`(uptime)`
echo -e "${dt}\n"

```

Suggest a read through of the docs:  https://docs.luxonis.com/software/ros/depthai-ros/

**Comment by Jai-GAY** [comment]
I appreciate your response.

> depthai_ros_driver package has default calibrations for the Luxonis Oak-D-lite and Oak-D-W97 cameras which are used if not specified in the launch.

I see. I was trying to reference your [ROS2 Aruco Markers](https://github.com/slowrunner/GoPi5Go/tree/main/systests/aruco#ros2-aruco-markers) example. Under that section, so now I think is not camera calibration data. 

> pi@GoPi5Go:DOCKER:~/GoPi5Go/ros2ws $ ros2 launch depthai_ros_driver aruco_camera.launch.py camera_model:=OAK-D-W params_file:=/home/pi/GoPi5Go/ros2ws/params/camera.yaml

May I know the function of this camera.yaml? Where can I get the camera.yaml for the Aruco Marker example?

**Comment by slowrunner** [comment]
> May I know the function of this camera.yaml? Where can I get the camera.yaml for the Aruco Marker example?

The camera.yaml did not change when I changed to AprilTag recognition.  By the way, the AprilTags work much, much, much better than Aruco markers.

To understand parameter files such as camera.yaml, you always need to look at the launch file to see what the defaults for ALL parameters are, and which few parameters are getting set by the passed parameter file.  In this case the parameters are actually for the camera and not for the aruco detection node at all that I can see.  There is a different param file aruco_tracker.yaml that perhaps was used at one point.  I ended up  preferring to use AprilTags so I didn't mess with AruCo markers much.

```
/oak:
  ros__parameters:
    camera:
      i_enable_imu: true
      i_enable_ir: false
      i_nn_type: spatial
      i_pipeline_type: RGBD
      cam_pos_x: 0.08
      cam_pos_z: 0.162
      use_rviz: false
    nn:
      i_nn_config_path: depthai_ros_driver/mobilenet
    rgb:
      i_low_bandwidth: true
    left:
      i_low_bandwidth: true
    right:
      i_low_bandwidth: true
    stereo:
      i_low_bandwidth: true
```
